-- begin CINEMACHAIN_TICKET
create unique index IDX_CINEMACHAIN_TICKET_UNIQ_TICKET_ID on CINEMACHAIN_TICKET (TICKET_ID)^
-- end CINEMACHAIN_TICKET
-- begin CINEMACHAIN_ORDER
alter table CINEMACHAIN_ORDER add constraint FK_CINEMACHAIN_ORDER_ON_CLIENT foreign key (CLIENT_ID) references CINEMACHAIN_CLIENT(ID)^
alter table CINEMACHAIN_ORDER add constraint FK_CINEMACHAIN_ORDER_ON_TICKET foreign key (TICKET_ID) references CINEMACHAIN_TICKET(ID)^
create index IDX_CINEMACHAIN_ORDER_ON_CLIENT on CINEMACHAIN_ORDER (CLIENT_ID)^
create index IDX_CINEMACHAIN_ORDER_ON_TICKET on CINEMACHAIN_ORDER (TICKET_ID)^
-- end CINEMACHAIN_ORDER
-- begin CINEMACHAIN_CLIENT
create unique index IDX_CINEMACHAIN_CLIENT_UNIQ_EMAIL on CINEMACHAIN_CLIENT (EMAIL)^
create unique index IDX_CINEMACHAIN_CLIENT_UNIQ_CLIENT_ID on CINEMACHAIN_CLIENT (CLIENT_ID)^
-- end CINEMACHAIN_CLIENT
