alter table CINEMACHAIN_ORDER add constraint FK_CINEMACHAIN_ORDER_ON_CLIENT foreign key (CLIENT_ID) references CINEMACHAIN_CLIENT(ID);
alter table CINEMACHAIN_ORDER add constraint FK_CINEMACHAIN_ORDER_ON_TICKET foreign key (TICKET_ID) references CINEMACHAIN_TICKET(ID);
create index IDX_CINEMACHAIN_ORDER_ON_CLIENT on CINEMACHAIN_ORDER (CLIENT_ID);
create index IDX_CINEMACHAIN_ORDER_ON_TICKET on CINEMACHAIN_ORDER (TICKET_ID);
